"""Initial migration with all models

Revision ID: 7cd15bd2f4aa
Revises: 
Create Date: 2025-11-09 13:30:21.511571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd15bd2f4aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vendedor', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_contador', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_contador')
        batch_op.drop_column('is_vendedor')

    # ### end Alembic commands ###
