"""Añadir modelos del sistema de ventas

Revision ID: 99a8a08c1415
Revises: c76bca87d0c6
Create Date: 2025-11-09 18:24:55.659242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99a8a08c1415'
down_revision = 'c76bca87d0c6'
branch_labels = None
depends_on = None

def safe_drop_index(table_name, index_name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name not in insp.get_table_names():
        return
    index_names = {idx.get('name') for idx in insp.get_indexes(table_name)}
    if index_name in index_names:
        op.drop_index(index_name, table_name=table_name)


def safe_drop_fk(table_name, constraint_name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name not in insp.get_table_names():
        return
    fk_names = {fk.get('name') for fk in insp.get_foreign_keys(table_name)}
    if constraint_name in fk_names:
        op.drop_constraint(constraint_name, table_name=table_name, type_='foreignkey')


def safe_drop_table(table_name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name in insp.get_table_names():
        # Entornos legacy pueden tener FKs cruzadas fuera de Alembic.
        # Se desactivan temporalmente para evitar fallos al limpiar tablas antiguas.
        try:
            bind.execute(sa.text("SET FOREIGN_KEY_CHECKS=0"))
            op.drop_table(table_name)
        finally:
            bind.execute(sa.text("SET FOREIGN_KEY_CHECKS=1"))


def upgrade():
    bind = op.get_bind()
    insp = sa.inspect(bind)

    # Entornos con cambios manuales pueden tener esta migracion aplicada de forma parcial.
    # Si la estructura objetivo principal ya existe, salimos sin reprocesar.
    table_names = set(insp.get_table_names())
    if {'cliente', 'venta', 'pago'}.issubset(table_names):
        cliente_cols = {c['name'] for c in insp.get_columns('cliente')}
        venta_cols = {c['name'] for c in insp.get_columns('venta')}
        pago_cols = {c['name'] for c in insp.get_columns('pago')}
        already_migrated = (
            'tipo_identificacion' in cliente_cols and
            'numero_venta' in venta_cols and
            'vendedor_id' in venta_cols and
            'numero_pago' in pago_cols
        )
        if already_migrated:
            return

    # ### commands auto generated by Alembic - please adjust! ###
    safe_drop_index('producto', 'ix_producto_codigo')
    safe_drop_table('producto')
    safe_drop_index('recoleccion_diaria', 'ix_recoleccion_diaria_fecha_recoleccion')
    safe_drop_table('recoleccion_diaria')
    safe_drop_table('categoria_producto')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_identificacion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('numero_identificacion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.alter_column('limite_credito',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        safe_drop_index('cliente', 'ix_cliente_codigo')
        safe_drop_index('cliente', 'ix_cliente_documento')
        batch_op.create_index(batch_op.f('ix_cliente_numero_identificacion'), ['numero_identificacion'], unique=True)
        batch_op.drop_column('codigo')
        batch_op.drop_column('created_at')
        batch_op.drop_column('documento')
        batch_op.drop_column('saldo_actual')

    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_pago', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('recibido_por', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('forma_pago', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('referencia', sa.String(length=100), nullable=True))
        batch_op.alter_column('venta_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('monto',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        safe_drop_index('pago', 'ix_pago_numero_recibo')
        batch_op.create_index(batch_op.f('ix_pago_numero_pago'), ['numero_pago'], unique=True)
        safe_drop_fk('pago', 'pago_ibfk_3')
        batch_op.create_foreign_key(None, 'user', ['recibido_por'], ['id'])
        batch_op.drop_column('numero_recibo')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('metodo_pago')
        batch_op.drop_column('estado')

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_venta', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('vendedor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tipo_pago', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True))
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('descuento',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        safe_drop_index('venta', 'ix_venta_numero_factura')
        batch_op.create_index(batch_op.f('ix_venta_numero_venta'), ['numero_venta'], unique=True)
        safe_drop_fk('venta', 'venta_ibfk_2')
        batch_op.create_foreign_key(None, 'user', ['vendedor_id'], ['id'])
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('numero_factura')
        batch_op.drop_column('tipo_venta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_venta', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('numero_factura', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('venta_ibfk_2'), 'user', ['usuario_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_venta_numero_venta'))
        batch_op.create_index(batch_op.f('ix_venta_numero_factura'), ['numero_factura'], unique=True)
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('descuento',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('subtotal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('fecha_vencimiento')
        batch_op.drop_column('tipo_pago')
        batch_op.drop_column('vendedor_id')
        batch_op.drop_column('numero_venta')

    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('metodo_pago', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('numero_recibo', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pago_ibfk_3'), 'user', ['usuario_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_pago_numero_pago'))
        batch_op.create_index(batch_op.f('ix_pago_numero_recibo'), ['numero_recibo'], unique=True)
        batch_op.alter_column('monto',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('venta_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('referencia')
        batch_op.drop_column('forma_pago')
        batch_op.drop_column('recibido_por')
        batch_op.drop_column('numero_pago')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_actual', mysql.DECIMAL(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('documento', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('codigo', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('ix_cliente_numero_identificacion'))
        batch_op.create_index(batch_op.f('ix_cliente_documento'), ['documento'], unique=True)
        batch_op.create_index(batch_op.f('ix_cliente_codigo'), ['codigo'], unique=True)
        batch_op.alter_column('limite_credito',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               nullable=False)
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('numero_identificacion')
        batch_op.drop_column('tipo_identificacion')

    op.create_table('categoria_producto',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('precio_base', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recoleccion_diaria',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha_recoleccion', sa.DATE(), nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cantidad_recolectada', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('recoleccion_diaria_ibfk_1')),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name=op.f('recoleccion_diaria_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('recoleccion_diaria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recoleccion_diaria_fecha_recoleccion'), ['fecha_recoleccion'], unique=False)

    op.create_table('producto',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('codigo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('unidad_medida', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('precio_venta', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock_actual', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('stock_minimo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_producto.id'], name=op.f('producto_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_codigo'), ['codigo'], unique=True)

    # ### end Alembic commands ###


