"""Add egg inventory models: categories, collection batches, eggs

Revision ID: c76bca87d0c6
Revises: 4ce3aac83409
Create Date: 2025-11-09 15:00:38.366512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c76bca87d0c6'
down_revision = '4ce3aac83409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_huevo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('peso_min', sa.Float(), nullable=False),
    sa.Column('peso_max', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_huevos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=True),
    sa.Column('cantidad_vendida', sa.Integer(), nullable=True),
    sa.Column('cantidad_rota', sa.Integer(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_huevo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_recoleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_lote', sa.String(length=20), nullable=False),
    sa.Column('fecha_recoleccion', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('hora_fin', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('total_huevos', sa.Integer(), nullable=True),
    sa.Column('total_peso', sa.Float(), nullable=True),
    sa.Column('huevos_rotos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_lote')
    )
    op.create_table('huevo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('roto', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('vendido', sa.Boolean(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_huevo.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_recoleccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movimiento_inventario')
    op.drop_table('item_venta')
    op.drop_table('categoria_producto')
    with op.batch_alter_table('recoleccion_diaria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recoleccion_diaria_fecha_recoleccion'))

    op.drop_table('recoleccion_diaria')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_numero_factura'))

    op.drop_table('venta')
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pago_numero_recibo'))

    op.drop_table('pago')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_codigo'))
        batch_op.drop_index(batch_op.f('ix_cliente_documento'))

    op.drop_table('cliente')
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_codigo'))

    op.drop_table('producto')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_numero_identificacion'), ['numero_identificacion'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_numero_identificacion'))

    op.create_table('producto',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('codigo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('unidad_medida', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('precio_venta', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock_actual', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('stock_minimo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_producto.id'], name='producto_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_codigo'), ['codigo'], unique=True)

    op.create_table('cliente',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('codigo', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('apellido', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('documento', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('direccion', mysql.TEXT(), nullable=True),
    sa.Column('limite_credito', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('saldo_actual', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_documento'), ['documento'], unique=True)
        batch_op.create_index(batch_op.f('ix_cliente_codigo'), ['codigo'], unique=True)

    op.create_table('pago',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('numero_recibo', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('venta_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('monto', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('fecha_pago', mysql.DATETIME(), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('pago_ibfk_1')),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name=op.f('pago_ibfk_3')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('pago_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pago_numero_recibo'), ['numero_recibo'], unique=True)

    op.create_table('venta',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('numero_factura', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha_venta', mysql.DATETIME(), nullable=True),
    sa.Column('subtotal', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('descuento', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('tipo_venta', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='venta_ibfk_1'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='venta_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_numero_factura'), ['numero_factura'], unique=True)

    op.create_table('recoleccion_diaria',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha_recoleccion', sa.DATE(), nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cantidad_recolectada', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('recoleccion_diaria_ibfk_1')),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name=op.f('recoleccion_diaria_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('recoleccion_diaria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recoleccion_diaria_fecha_recoleccion'), ['fecha_recoleccion'], unique=False)

    op.create_table('categoria_producto',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('precio_base', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('item_venta',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('venta_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('item_venta_ibfk_2')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('item_venta_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('movimiento_inventario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tipo_movimiento', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('motivo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha_movimiento', mysql.DATETIME(), nullable=True),
    sa.Column('stock_anterior', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('stock_nuevo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('movimiento_inventario_ibfk_1')),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name=op.f('movimiento_inventario_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('huevo')
    op.drop_table('lote_recoleccion')
    op.drop_table('inventario_huevos')
    op.drop_table('categoria_huevo')
    # ### end Alembic commands ###
